In [1]:
import pandas as pd

#### chager un échantillon

In [2]:
df = pd.read_csv("data/raw/dvf2025.txt", sep="|", encoding="utf-8", low_memory=False)

In [3]:
df

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,78.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,1.0,Maison,NaN,111.0,5.0,S,NaN,133.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,3.0,Dépendance,NaN,0.0,0.0,S,NaN,133.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,46.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,27/06/2025,Vente,...,NaN,2,2.0,Appartement,NaN,61.0,3.0,NaN,NaN,NaN
1387073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,27/06/2025,Vente,...,NaN,2,2.0,Appartement,NaN,47.0,2.0,NaN,NaN,NaN
1387074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,27/06/2025,Vente,...,NaN,2,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN
1387075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,25/06/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1387076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,25/06/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print("Shape:", df.shape)

Shape: (1387077, 43)

In [5]:
print("Colonnes:", df.columns.tolist())

Colonnes: ['Identifiant de document', 'Reference document', '1 Articles CGI', '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI', 'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere', 'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Prefixe de section', 'Section', 'No plan', 'No Volume', '1er lot', 'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot', '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot', 'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot', 'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local', 'Surface reelle bati', 'Nombre pieces principales', 'Nature culture', 'Nature culture speciale', 'Surface terrain']

In [6]:
print("Types:", df.dtypes)

Types: Identifiant de document       float64
Reference document            float64
1 Articles CGI                float64
2 Articles CGI                float64
3 Articles CGI                float64
4 Articles CGI                float64
5 Articles CGI                float64
No disposition                  int64
Date mutation                     str
Nature mutation                   str
Valeur fonciere                   str
No voie                       float64
B/T/Q                             str
Type de voie                      str
Code voie                         str
Voie                              str
Code postal                   float64
Commune                           str
Code departement                  str
Code commune                    int64
Prefixe de section            float64
Section                           str
No plan                         int64
No Volume                         str
1er lot                           str
Surface Carrez du 1er lot         str
2eme lot                          str
Surface Carrez du 2eme lot        str
3eme lot                          str
Surface Carrez du 3eme lot        str
4eme lot                      float64
Surface Carrez du 4eme lot        str
5eme lot                      float64
Surface Carrez du 5eme lot        str
Nombre de lots                  int64
Code type local               float64
Type local                        str
Identifiant local             float64
Surface reelle bati           float64
Nombre pieces principales     float64
Nature culture                    str
Nature culture speciale           str
Surface terrain               float64
dtype: object

In [7]:
print("Nulls:", df.isnull().sum())

Nulls: Identifiant de document       1387077
Reference document            1387077
1 Articles CGI                1387077
2 Articles CGI                1387077
3 Articles CGI                1387077
4 Articles CGI                1387077
5 Articles CGI                1387077
No disposition                      0
Date mutation                       0
Nature mutation                     0
Valeur fonciere                 13995
No voie                        513979
B/T/Q                         1322557
Type de voie                   542232
Code voie                       12158
Voie                            12171
Code postal                     12231
Commune                             0
Code departement                    0
Code commune                        0
Prefixe de section            1316580
Section                            56
No plan                             0
No Volume                     1384014
1er lot                        944993
Surface Carrez du 1er lot     1251644
2eme lot                      1248916
Surface Carrez du 2eme lot    1342513
3eme lot                      1361188
Surface Carrez du 3eme lot    1381838
4eme lot                      1376995
Surface Carrez du 4eme lot    1385365
5eme lot                      1381027
Surface Carrez du 5eme lot    1386317
Nombre de lots                      0
Code type local                572338
Type local                     572338
Identifiant local             1387077
Surface reelle bati            573187
Nombre pieces principales      573187
Nature culture                 447624
Nature culture speciale       1325533
Surface terrain                447624
dtype: int64

In [8]:
df.head()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,78.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,1.0,Maison,NaN,111.0,5.0,S,NaN,133.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,07/01/2025,Vente,...,NaN,0,3.0,Dépendance,NaN,0.0,0.0,S,NaN,133.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,46.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,06/01/2025,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,J,NaN,17.0

#### Calcul prix au m² (avant nettoyage)

In [9]:
# Nettoyer et convertir valeur_fonciere
df["Valeur fonciere"] = (
    df["Valeur fonciere"]
    .str.replace(",", ".", regex=False)   # remplace la virgule par un point
    .str.replace(" ", "", regex=False)    # supprime les espaces éventuels
)
df["Valeur fonciere"] = pd.to_numeric(df["Valeur fonciere"], errors="coerce")

df["prix_m2"] = df["Valeur fonciere"] / df["Surface reelle bati"]

#### Stats par type de bien

In [11]:
# Garder uniquement les lignes avec un prix_m2 valide et plausible
df_propre = df[
    df["prix_m2"].notna() &          # pas de NaN
    (df["prix_m2"] > 100) &          # prix minimum plausible €/m²
    (df["prix_m2"] < 50000)          # prix maximum plausible €/m²
].copy()

# Relancer le describe sur les données propres
df_propre.groupby("Type local")["prix_m2"].describe()

,count,mean,std,min,25%,50%,75%,max
Type local,,,,,,,,
Appartement,176537.0,5146.854932,5516.410738,101.010101,2254.901961,3558.823529,5778.414634,49934.292857
Local industriel. commercial ou assimilé,36279.0,5603.243016,8406.968379,100.250627,1022.727273,2403.846154,5833.333333,49996.000000
Maison,216077.0,2866.457539,3143.700564,100.020000,1445.400000,2191.919192,3262.805556,49897.882979

#### Distribution des prix

In [12]:
df["Valeur fonciere"].describe()

count    1.373082e+06
mean     7.034421e+05
std      4.944190e+06
min      1.500000e-01
25%      5.935000e+04
50%      1.580000e+05
75%      2.950000e+05
max      3.172908e+08
Name: Valeur fonciere, dtype: float64

#### Top 10 communes en volume de transactions

In [14]:
df["Commune"].value_counts().head(10)

Commune
NICE           9953
TOULOUSE       8464
BORDEAUX       5571
MONTPELLIER    5158
NANTES         4673
NIMES          3752
LILLE          3710
RENNES         3634
CABOURG        3575
TOULON         3444
Name: count, dtype: int64